apiVersion: v1
kind: Pod
metadata:
  name: pod-limitado
  labels: 
    run: pod-limitado
spec: 
  containers:
  - name: pod-limitado
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"  
